version: '2'
services:
  auth-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/auth/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=auth
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
